package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Table(name = "PA_BP_Approval")
public class BusinessPartnerApproval
		extends
			org.drools.persistence.jpa.marshaller.VariableEntity
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BUSINESSPARTNERAPPROVAL_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "BUSINESSPARTNERAPPROVAL_ID_GENERATOR", sequenceName = "BUSINESSPARTNERAPPROVAL_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Business Partner Approval")
	private java.lang.Boolean bp_approved;

	@org.kie.api.definition.type.Label("Business Partner Comments")
	private java.lang.String bp_comments;

	public BusinessPartnerApproval() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Boolean getBp_approved() {
		return this.bp_approved;
	}

	public void setBp_approved(java.lang.Boolean bp_approved) {
		this.bp_approved = bp_approved;
	}

	public java.lang.String getBp_comments() {
		return this.bp_comments;
	}

	public void setBp_comments(java.lang.String bp_comments) {
		this.bp_comments = bp_comments;
	}

	public BusinessPartnerApproval(java.lang.Long id,
			java.lang.Boolean bp_approved, java.lang.String bp_comments) {
		this.id = id;
		this.bp_approved = bp_approved;
		this.bp_comments = bp_comments;
	}

}