package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "PA_Admin_1_Approval")
public class FirstAdminApproval extends 
org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "FIRSTADMINAPPROVAL_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "FIRSTADMINAPPROVAL_ID_GENERATOR", sequenceName = "FIRSTADMINAPPROVAL_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Admin Approval")
	private java.lang.Boolean admin_1_approval;

	@org.kie.api.definition.type.Label(value = "Admin Review Commnets")
	private java.lang.String admin_1_comments;

	public FirstAdminApproval() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Boolean getAdmin_1_approval() {
		return this.admin_1_approval;
	}

	public void setAdmin_1_approval(java.lang.Boolean admin_1_approval) {
		this.admin_1_approval = admin_1_approval;
	}

	public java.lang.String getAdmin_1_comments() {
		return this.admin_1_comments;
	}

	public void setAdmin_1_comments(java.lang.String admin_1_comments) {
		this.admin_1_comments = admin_1_comments;
	}

	public FirstAdminApproval(java.lang.Long id,
			java.lang.Boolean admin_1_approval,
			java.lang.String admin_1_comments) {
		this.id = id;
		this.admin_1_approval = admin_1_approval;
		this.admin_1_comments = admin_1_comments;
	}

}