package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "PA_Requestor_Approval")
public class RequestorApproval extends 
org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "REQUESTORAPPROVAL_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "REQUESTORAPPROVAL_ID_GENERATOR", sequenceName = "REQUESTORAPPROVAL_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Requestor Approval")
	private java.lang.Boolean requestor_approval;

	@org.kie.api.definition.type.Label(value = "Requester Review Comments")
	private java.lang.String requestor_comments;

	public RequestorApproval() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Boolean getRequestor_approval() {
		return this.requestor_approval;
	}

	public void setRequestor_approval(java.lang.Boolean requestor_approval) {
		this.requestor_approval = requestor_approval;
	}

	public java.lang.String getRequestor_comments() {
		return this.requestor_comments;
	}

	public void setRequestor_comments(java.lang.String requestor_comments) {
		this.requestor_comments = requestor_comments;
	}

	public RequestorApproval(java.lang.Long id,
			java.lang.Boolean requestor_approval,
			java.lang.String requestor_comments) {
		this.id = id;
		this.requestor_approval = requestor_approval;
		this.requestor_comments = requestor_comments;
	}

}