package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "PA_Admin_2_Approval")
public class SecondAdminApproval extends 
org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SECONDADMINAPPROVAL_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SECONDADMINAPPROVAL_ID_GENERATOR", sequenceName = "SECONDADMINAPPROVAL_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Admin Approval")
	private java.lang.Boolean admin_2_approval;

	@org.kie.api.definition.type.Label(value = "Admin Review Commnets")
	private java.lang.String comments;

	public SecondAdminApproval() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Boolean getAdmin_2_approval() {
		return this.admin_2_approval;
	}

	public void setAdmin_2_approval(java.lang.Boolean admin_2_approval) {
		this.admin_2_approval = admin_2_approval;
	}

	public java.lang.String getComments() {
		return this.comments;
	}

	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public SecondAdminApproval(java.lang.Long id,
			java.lang.Boolean admin_2_approval, java.lang.String comments) {
		this.id = id;
		this.admin_2_approval = admin_2_approval;
		this.comments = comments;
	}

}