package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Table(name = "PA_Vendor_Evaluation")
@javax.persistence.Entity
public class VendorEvaluation
		extends
			org.drools.persistence.jpa.marshaller.VariableEntity
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "VENDOREVALUATION_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "VENDOREVALUATION_ID_GENERATOR", sequenceName = "VENDOREVALUATION_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Vendor Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Vendor Address")
	private java.lang.String address;

	@org.kie.api.definition.type.Label("Comments About Vendor")
	private java.lang.String comments;

	@org.kie.api.definition.type.Label("Vendor Quoted Price")
	private java.lang.Double price;

	@org.kie.api.definition.type.Label("Vendor Warranty Details")
	private java.lang.String warranty;

	@org.kie.api.definition.type.Label("Expected Delivery Date From Vendor")
	private java.util.Date date;

	public VendorEvaluation() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getComments() {
		return this.comments;
	}

	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(java.lang.String warranty) {
		this.warranty = warranty;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public VendorEvaluation(java.lang.Long id, java.lang.String name,
			java.lang.String address, java.lang.String comments,
			java.lang.Double price, java.lang.String warranty,
			java.util.Date date) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.comments = comments;
		this.price = price;
		this.warranty = warranty;
		this.date = date;
	}

}