package com.myteam.pa;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PRDetails extends 
org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRDETAILS_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PRDETAILS_ID_GENERATOR", sequenceName = "PRDETAILS_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String name;

	private java.lang.Integer count;

	private double price;

	public PRDetails() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getCount() {
		return this.count;
	}

	public void setCount(java.lang.Integer count) {
		this.count = count;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public PRDetails(java.lang.Long id, java.lang.String name,
			java.lang.Integer count, double price) {
		this.id = id;
		this.name = name;
		this.count = count;
		this.price = price;
	}

}