package com.myteam.pa;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PRVendorList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRVENDORLIST_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PRVENDORLIST_ID_GENERATOR", sequenceName = "PRVENDORLIST_ID_SEQ")
	private java.lang.Long id;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<com.myteam.pa.PRVendor> vendorList;

	public PRVendorList() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<com.myteam.pa.PRVendor> getVendorList() {
		return this.vendorList;
	}

	public void setVendorList(java.util.List<com.myteam.pa.PRVendor> vendorList) {
		this.vendorList = vendorList;
	}

	public PRVendorList(java.lang.Long id,
			java.util.List<com.myteam.pa.PRVendor> vendorList) {
		this.id = id;
		this.vendorList = vendorList;
	}

}