package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PA_VENDOR_HEADER implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PA_VENDOR_HEADER_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PA_VENDOR_HEADER_ID_GENERATOR", sequenceName = "PA_VENDOR_HEADER_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Purchase Order Number")
	private java.lang.String po_number;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Vendor Details List")
	private java.util.List<com.myteam.procurementautomation.PA_VENDOR_DETAIL> vendor_detail;

	private Long task_id;

	private Long process_instance_id;

	private java.lang.String process_definition_id;

	public PA_VENDOR_HEADER() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getPo_number() {
		return this.po_number;
	}

	public void setPo_number(java.lang.String po_number) {
		this.po_number = po_number;
	}

	public java.util.List<com.myteam.procurementautomation.PA_VENDOR_DETAIL> getVendor_detail() {
		return this.vendor_detail;
	}

	public void setVendor_detail(
			java.util.List<com.myteam.procurementautomation.PA_VENDOR_DETAIL> vendor_detail) {
		this.vendor_detail = vendor_detail;
	}

	public java.lang.String getProcess_definition_id() {
		return this.process_definition_id;
	}

	public void setProcess_definition_id(java.lang.String process_definition_id) {
		this.process_definition_id = process_definition_id;
	}

	public java.lang.Long getTask_id() {
		return this.task_id;
	}

	public void setTask_id(java.lang.Long task_id) {
		this.task_id = task_id;
	}

	@Override
	public String toString() {
		return "PA_VENDOR_HEADER [id=" + id.toString() + ", po_number="+ po_number + ", vendor_detail=" + vendor_detail + ", task_id="+ task_id.toString() + ", process_instance_id="+ process_instance_id.toString() + ", process_definition_id="+ process_definition_id + "]";
	}

	public java.lang.Long getProcess_instance_id() {
		return this.process_instance_id;
	}

	public void setProcess_instance_id(java.lang.Long process_instance_id) {
		this.process_instance_id = process_instance_id;
	}

	public PA_VENDOR_HEADER(
			java.lang.Long id,
			java.lang.String po_number,
			java.util.List<com.myteam.procurementautomation.PA_VENDOR_DETAIL> vendor_detail,
			java.lang.Long task_id, java.lang.Long process_instance_id,
			java.lang.String process_definition_id) {
		this.id = id;
		this.po_number = po_number;
		this.vendor_detail = vendor_detail;
		this.task_id = task_id;
		this.process_instance_id = process_instance_id;
		this.process_definition_id = process_definition_id;
	}

}