package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PA_VENDOR_DETAIL  implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PA_VENDOR_DETAIL_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PA_VENDOR_DETAIL_ID_GENERATOR", sequenceName = "PA_VENDOR_DETAIL_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Vendor Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "Vendor Address")
	private java.lang.String address;

	@org.kie.api.definition.type.Label(value = "Vendor Location")
	private java.lang.String location;

	@org.kie.api.definition.type.Label(value = "Vendor Warranty Details")
	private java.lang.String warranty;

	public PA_VENDOR_DETAIL() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(java.lang.String warranty) {
		this.warranty = warranty;
	}

	public PA_VENDOR_DETAIL(java.lang.Long id, java.lang.String name,
			java.lang.String address, java.lang.String location,
			java.lang.String warranty) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.location = location;
		this.warranty = warranty;
	}

@Override
    public String toString() {
        return "PA_VENDOR_DETAIL [id=" + id + ", name=" + name + ", address=" + address + ", location=" + location + ", warranty=" + warranty + "]";
    }   

}