package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BUVendorEvaluationDetails
		extends
			org.drools.persistence.jpa.marshaller.VariableEntity
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "BUVENDOREVALUATIONDETAILS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "BUVENDOREVALUATIONDETAILS_ID_GENERATOR", sequenceName = "BUVENDOREVALUATIONDETAILS_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "First Level Approval")
	private java.lang.String first_approval;

	@org.kie.api.definition.type.Label(value = "Second Level Approval")
	private java.lang.String second_approval;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Label(value = "Vendor Eveluation List")
	private java.util.List<com.myteam.procurementautomation.VendorEvaluation> vendorevaluationlist;

	public BUVendorEvaluationDetails() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFirst_approval() {
		return this.first_approval;
	}

	public void setFirst_approval(java.lang.String first_approval) {
		this.first_approval = first_approval;
	}

	public java.lang.String getSecond_approval() {
		return this.second_approval;
	}

	public void setSecond_approval(java.lang.String second_approval) {
		this.second_approval = second_approval;
	}

	public java.util.List<com.myteam.procurementautomation.VendorEvaluation> getVendorevaluationlist() {
		return this.vendorevaluationlist;
	}

	public void setVendorevaluationlist(
			java.util.List<com.myteam.procurementautomation.VendorEvaluation> vendorevaluationlist) {
		this.vendorevaluationlist = vendorevaluationlist;
	}

	public BUVendorEvaluationDetails(
			java.lang.Long id,
			java.lang.String first_approval,
			java.lang.String second_approval,
			java.util.List<com.myteam.procurementautomation.VendorEvaluation> vendorevaluationlist) {
		this.id = id;
		this.first_approval = first_approval;
		this.second_approval = second_approval;
		this.vendorevaluationlist = vendorevaluationlist;
	}

}