package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RequisitionDetails
		extends
			org.drools.persistence.jpa.marshaller.VariableEntity
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "REQUISITIONDETAILS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "REQUISITIONDETAILS_ID_GENERATOR", sequenceName = "REQUISITIONDETAILS_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Requested Item Details")
	private java.lang.String item_det;

	@org.kie.api.definition.type.Label(value = "Associated Project and Program Details")
	private java.lang.String project_info;

	@org.kie.api.definition.type.Label(value = "Existing Vendor Details Associated With This Request")
	private java.lang.String existing_vendor_info;

	@org.kie.api.definition.type.Label(value = "Required Date")
	private java.util.Date required_date;

	public RequisitionDetails() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getItem_det() {
		return this.item_det;
	}

	public void setItem_det(java.lang.String item_det) {
		this.item_det = item_det;
	}

	public java.lang.String getProject_info() {
		return this.project_info;
	}

	public void setProject_info(java.lang.String project_info) {
		this.project_info = project_info;
	}

	public java.lang.String getExisting_vendor_info() {
		return this.existing_vendor_info;
	}

	public void setExisting_vendor_info(java.lang.String existing_vendor_info) {
		this.existing_vendor_info = existing_vendor_info;
	}

	public java.util.Date getRequired_date() {
		return this.required_date;
	}

	public void setRequired_date(java.util.Date required_date) {
		this.required_date = required_date;
	}

	public RequisitionDetails(java.lang.Long id, java.lang.String item_det,
			java.lang.String project_info,
			java.lang.String existing_vendor_info, java.util.Date required_date) {
		this.id = id;
		this.item_det = item_det;
		this.project_info = project_info;
		this.existing_vendor_info = existing_vendor_info;
		this.required_date = required_date;
	}

}