package com.myteam.institutionmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class department extends 
org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DEPARTMENT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "DEPARTMENT_ID_GENERATOR", sequenceName = "DEPARTMENT_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String departmentname;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<com.myteam.institutionmanagement.section> sectioninfo;

	public department() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getDepartmentname() {
		return this.departmentname;
	}

	public void setDepartmentname(java.lang.String departmentname) {
		this.departmentname = departmentname;
	}

	public java.util.List<com.myteam.institutionmanagement.section> getSectioninfo() {
		return this.sectioninfo;
	}

	public void setSectioninfo(
			java.util.List<com.myteam.institutionmanagement.section> sectioninfo) {
		this.sectioninfo = sectioninfo;
	}

	public department(java.lang.Long id, java.lang.String departmentname,
			java.util.List<com.myteam.institutionmanagement.section> sectioninfo) {
		this.id = id;
		this.departmentname = departmentname;
		this.sectioninfo = sectioninfo;
	}

}