package com.myteam.institutionmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class section extends 
org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private int count;
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SECTION_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SECTION_ID_GENERATOR", sequenceName = "SECTION_ID_SEQ")
	private java.lang.Long id;

	public section() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public section(java.lang.String name, int count, java.lang.Long id) {
		this.name = name;
		this.count = count;
		this.id = id;
	}

}