package com.myteam.pa;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PRheader
		extends
			org.drools.persistence.jpa.marshaller.VariableEntity
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRHEADER_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PRHEADER_ID_GENERATOR", sequenceName = "PRHEADER_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String requestorname;

	private java.lang.String email;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<com.myteam.pa.PRDetails> details;

	public PRheader() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getRequestorname() {
		return this.requestorname;
	}

	public void setRequestorname(java.lang.String requestorname) {
		this.requestorname = requestorname;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.util.List<com.myteam.pa.PRDetails> getDetails() {
		return this.details;
	}

	public void setDetails(java.util.List<com.myteam.pa.PRDetails> details) {
		this.details = details;
	}

	public PRheader(java.lang.Long id, java.lang.String requestorname,
			java.lang.String email,
			java.util.List<com.myteam.pa.PRDetails> details) {
		this.id = id;
		this.requestorname = requestorname;
		this.email = email;
		this.details = details;
	}

}