package com.myteam.ab;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class college implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "COLLEGE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "COLLEGE_ID_GENERATOR", sequenceName = "COLLEGE_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String name;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<com.myteam.ab.staff> stafflist;

	public college() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.List<com.myteam.ab.staff> getStafflist() {
		return this.stafflist;
	}

	public void setStafflist(java.util.List<com.myteam.ab.staff> stafflist) {
		this.stafflist = stafflist;
	}

	public college(java.lang.Long id, java.lang.String name,
			java.util.List<com.myteam.ab.staff> stafflist) {
		this.id = id;
		this.name = name;
		this.stafflist = stafflist;
	}

}