package com.myteam.ab;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class staff implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "STAFF_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "STAFF_ID_GENERATOR", sequenceName = "STAFF_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String name;

	private java.lang.Integer salary;

	public staff() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getSalary() {
		return this.salary;
	}

	public void setSalary(java.lang.Integer salary) {
		this.salary = salary;
	}

	public staff(java.lang.Long id, java.lang.String name,
			java.lang.Integer salary) {
		this.id = id;
		this.name = name;
		this.salary = salary;
	}

}