package com.myteam.ab;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class student implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "STUDENT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "STUDENT_ID_GENERATOR", sequenceName = "STUDENT_ID_SEQ")
	private java.lang.Long id;

	private String name;

	private java.lang.Integer mark;

	public student() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getMark() {
		return this.mark;
	}

	public void setMark(java.lang.Integer mark) {
		this.mark = mark;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public student(java.lang.Long id, java.lang.String name,
			java.lang.Integer mark) {
		this.id = id;
		this.name = name;
		this.mark = mark;
	}

}