package com.myteam.hospital;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "employees")
public class employees extends org.drools.persistence.jpa.marshaller.VariableEntity
 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EMPLOYEES_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "EMPLOYEES_ID_GENERATOR", sequenceName = "EMPLOYEES_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String name;

	private int age;

	private int salary;

	public employees() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getSalary() {
		return this.salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	public employees(java.lang.Long id, java.lang.String name, int age,
			int salary) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.salary = salary;
	}
	@Override
    public String toString() {
        return "employees [id=" + id + ", name=" + name + ",, age=" + age + ", salary=" + salary + "]";
    }   

}