package com.myteam.hospital;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "employee")
public class employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "EMPLOYEE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "EMPLOYEE_ID_GENERATOR", sequenceName = "EMPLOYEE_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String department;

	private java.lang.String location;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER, orphanRemoval = false)
	private java.util.List<com.myteam.hospital.Staff> staffs;

	public employee() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getDepartment() {
		return this.department;
	}

	public void setDepartment(java.lang.String department) {
		this.department = department;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.util.List<com.myteam.hospital.Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(java.util.List<com.myteam.hospital.Staff> staffs) {
		this.staffs = staffs;
	}

	public employee(java.lang.Long id, java.lang.String department,
			java.lang.String location,
			java.util.List<com.myteam.hospital.Staff> staffs) {
		this.id = id;
		this.department = department;
		this.location = location;
		this.staffs = staffs;
	}

}