package com.myteam.vivek;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class coach extends org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "COACH_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "COACH_ID_GENERATOR", sequenceName = "COACH_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String name;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<com.myteam.vivek.sports> sport;

	public coach() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.List<com.myteam.vivek.sports> getSport() {
		return this.sport;
	}

	public void setSport(java.util.List<com.myteam.vivek.sports> sport) {
		this.sport = sport;
	}

	public coach(java.lang.Long id, java.lang.String name,
			java.util.List<com.myteam.vivek.sports> sport) {
		this.id = id;
		this.name = name;
		this.sport = sport;
	}

}