package com.myteam.vivek;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class team extends org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "TEAM_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "TEAM_ID_GENERATOR", sequenceName = "TEAM_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String teamname;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<com.myteam.vivek.players> player;

	public team() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getTeamname() {
		return this.teamname;
	}

	public void setTeamname(java.lang.String teamname) {
		this.teamname = teamname;
	}

	public java.util.List<com.myteam.vivek.players> getPlayer() {
		return this.player;
	}

	public void setPlayer(java.util.List<com.myteam.vivek.players> player) {
		this.player = player;
	}

	public team(java.lang.Long id, java.lang.String teamname,
			java.util.List<com.myteam.vivek.players> player) {
		this.id = id;
		this.teamname = teamname;
		this.player = player;
	}

}