package com.myteam.procurementautomation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "PA_Purchase_Request")
public class PurchaseRequest
		extends
			org.drools.persistence.jpa.marshaller.VariableEntity
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PURCHASEREQUEST_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PURCHASEREQUEST_ID_GENERATOR", sequenceName = "PURCHASEREQUEST_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Purchase Requestor Details")
	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private RequestorDetails requestorDetails;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Purchase Requistion Details")
	private java.util.List<com.myteam.procurementautomation.RequisitionDetails> requisitionDetails;

	public PurchaseRequest() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<com.myteam.procurementautomation.RequisitionDetails> getRequisitionDetails() {
		return this.requisitionDetails;
	}

	public void setRequisitionDetails(
			java.util.List<com.myteam.procurementautomation.RequisitionDetails> requisitionDetails) {
		this.requisitionDetails = requisitionDetails;
	}

	public com.myteam.procurementautomation.RequestorDetails getRequestorDetails() {
		return this.requestorDetails;
	}

	public void setRequestorDetails(
			com.myteam.procurementautomation.RequestorDetails requestorDetails) {
		this.requestorDetails = requestorDetails;
	}

	public PurchaseRequest(
			java.lang.Long id,
			com.myteam.procurementautomation.RequestorDetails requestorDetails,
			java.util.List<com.myteam.procurementautomation.RequisitionDetails> requisitionDetails) {
		this.id = id;
		this.requestorDetails = requestorDetails;
		this.requisitionDetails = requisitionDetails;
	}

}